name: heat_risk_app
description: AI Heat Risk Warning mobile app with route planning
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  permission_handler: ^11.3.1
  flutter_tts: ^4.2.2

flutter:
  uses-material-design: true
